### ISSUE TITLE
创建Qzone对象

### ISSUE THREAD

**Issue by WATjstHapen** [Smart-Hypercube/Qzone-API#15]
对不起，刚学习python有很多不明白，请问先生如何从Cookies文件中获得所需对象，有没有实例样本文件作为参考学习？
谢谢

**Comment by SmartHypercube** [comment]
获得一个网站的 cookies 有很多方法，可以自行搜索，例如这篇文章 https://blog.csdn.net/whatday/article/details/107098251 中的方法二就是一种很常见的做法。

无论用哪种方法，获取到的 cookies 应该是类似于 `a=1; b=2; c=3` 这样的字符串，里面有多个用分号隔开的部分。把这样的字符串保存在 Python 的一个变量中，假设变量名叫 `x`，那么可以这样创建一个 `Qzone` 对象：`y = qzone.Qzone(**qzone.cookie_str_to_dict(x))`。然后可以调用 `y.emotion_list` 方法。
