### ISSUE TITLE
可以添加获取好友动态信息吗

### ISSUE THREAD

**Issue by mooncakedevop** [Smart-Hypercube/Qzone-API#9]
自己最近也在用cookie尝试爬取说说，我想爬的是自己好友的说说信息，也就是登陆后好友动态的内容 然后做可视化分析。

**Comment by SmartHypercube** [comment]
我记得我没支持这个功能是有原因的，这个用的接口好像复杂一点，所以我最终采用的方案是对所有好友，分别获取他们发的所有说说。

你可以这样做：对每个好友，获取他的所有说说，这是有序的，你会先得到最新的，然后得到越来越旧的，当见到一条太旧的时（比如一个月前），停止获取，去处理下一个好友。这样最终就能获得一个月内所有好友的说说。

这个解决方案应该足以取代获取好友动态的接口。如果仍未解决你的需求，可以重新打开本 issue。
